trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - pipeline/*
    
pool:
  vmImage: windows-latest

parameters:
- name: uniqueId
  displayName: 'Resource Group of the AKS cluster'
  type: string
  default: 'todeltest7'
- name: resourceGroupLocation
  displayName: 'Resource Group of the AKS cluster'
  type: string
  default: 'australiaeast'


variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '24a407c8-9f78-441c-aa95-31a4e273e9a1'
  azureResourceManagerConnection: 'Visual Studio Enterprise (MSFT)(24a407c8-9f78-441c-aa95-31a4e273e9a1)'

  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/'

stages:
- stage: BuildInfra
  jobs:
  - job:
    steps:
    
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
        backendServiceArm: 'Visual Studio Enterprise (MSFT) (24a407c8-9f78-441c-aa95-31a4e273e9a1)'
        backendAzureRmResourceGroupName: 'tfstate'
        backendAzureRmStorageAccountName: 'tfstate12909'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'terraform.tfstate'