trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - pipeline/*
    
pool:
  vmImage: windows-latest

parameters:
- name: uniqueId
  displayName: 'Resource Group of the AKS cluster'
  type: string
  default: 'todeltest7'
- name: resourceGroupLocation
  displayName: 'Resource Group of the AKS cluster'
  type: string
  default: 'australiaeast'


variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '24a407c8-9f78-441c-aa95-31a4e273e9a1'
  azureResourceManagerConnection: 'Visual Studio Enterprise (MSFT)(24a407c8-9f78-441c-aa95-31a4e273e9a1)'

  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/'

stages:
- stage: BuildInfra
  jobs:
  - job: RunTerraformfile
    steps:
    
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
        backendServiceArm: 'Visual Studio Enterprise (MSFT) (24a407c8-9f78-441c-aa95-31a4e273e9a1)'
        backendAzureRmResourceGroupName: 'tfstate'
        backendAzureRmStorageAccountName: 'tfstate12909'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'terraform.tfstate'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
        environmentServiceNameAzureRM: 'Visual Studio Enterprise (MSFT) (24a407c8-9f78-441c-aa95-31a4e273e9a1)'


- stage: Build
  jobs:
  - job: logic_app_build
    displayName: 'Build and publish logic app'
    steps:
    - task: CopyFiles@2
      displayName: 'Create project folder'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/logicapp'
        Contents: |
          logic/**
        TargetFolder: 'project_output'

    - task: ArchiveFiles@2
      displayName: 'Create project zip'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/project_output/logic'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: PublishPipelineArtifact@1
      displayName: 'Publish project zip artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        artifact: '$(logicAppCIArtifactName)'
        publishLocation: 'pipeline'