trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - pipeline/*
    
pool:
  vmImage: windows-latest

parameters:
- name: uniqueId
  displayName: 'Resource Group of the AKS cluster'
  type: string
  default: 'todeltest7'
- name: resourceGroupLocation
  displayName: 'Resource Group of the AKS cluster'
  type: string
  default: 'australiaeast'


variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '24a407c8-9f78-441c-aa95-31a4e273e9a1'
  azureResourceManagerConnection: 'Visual Studio Enterprise (MSFT)(24a407c8-9f78-441c-aa95-31a4e273e9a1)'

  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/'

stages:
- stage: BuildInfra
  jobs:
  - job:
    steps:
    
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Subscription'
        azureResourceManagerConnection:  '$(azureResourceManagerConnection)'
        subscriptionId:  '$(azureSubscription)'
        location: 'Australia East'
        templateLocation: 'Linked artifact'
        csmFile: 'infra/main.bicep'
        overrideParameters: '-uniqueId ${{parameters.uniqueId}} -resourceGroupLocation ${{parameters.resourceGroupLocation}}'
        deploymentMode: 'Incremental'
        deploymentName: '$(Build.BuildNumber)'